name: Deploy Data

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Iniciando despliegue de Base de Datos..."
            
            # 1. Asegurar que estamos en el home y que el repo existe
            cd ~
            if [ ! -d "Data_Eval2" ]; then
              git clone https://github.com/Martin89899/Data_Eval2.git
            fi
            cd Data_Eval2

            # 2. Sincronizar código
            git pull origin main

            # 3. Reiniciar contenedores de Base de Datos
            # Usamos la ruta completa al binario que instalamos
            sudo /usr/local/bin/docker-compose down || true
            sudo /usr/local/bin/docker-compose up -d --build
            
            echo "¡Base de Datos desplegada con éxito!"